= Release management

== Release strategy
While the extension is under heavy development, the plan is to provide the newest features for the LTS and the most current version of quarkus.

The version of the axon framework will be updated as fast as possible.

The releases for the most current quarkus versions have the following pattern:

Major.Minor.Patchset

The releases for the latest LTS have a similar structure, but it is extended by the quarkus version. E.g., for the current Quarkus LTS Version 3.15.* the version of the extension is 0.1.1-3.15.

In the link:docs/modules/ROOT/pages/index.adoc[documentation].

== How To Release
Sadly, the setup GitHub workflow doesn't work. As long as the workflow doesn't work, the release is created manually on the local machine.

The following steps need to be followed.

For this example, version 0.4.1 should be released for the current and the latest quarkus version.

=== Set the gpg passphrase

This is a safe way to omit to have the password in the history of the terminal.

==== Mac(zsh)

[source,bash]
----
printf "Enter your GnuPG key passphrase: "; IFS= read -s GPG_PASSPHRASE
export MAVEN_GPG_PASSPHRASE=$GPG_PASSPHRASE
----

=== Release for the most current quarkus version
[source,bash]
----
git checkout main
mvn -P publish -B release:prepare release:perform -DreleaseVersion=0.4.1 -DdevelopmentVersion=0.5.0-SNAPSHOT
----

=== Release for the latest quarkus LTS version (deprecated)
[source,bash]
----
git checkout quarkus-3.15
read -s -p "Enter your GnuPG key passphrase: " MAVEN_GPG_PASSPHRASE
mvn -P ossrh -B release:prepare release:perform -DreleaseVersion=0.4.1-3.15 -DdevelopmentVersion=0.5.0-3.15-SNAPSHOT -Dgpg.passphrase="${GPG_PASSPHRASE}"
----

=== Unset the gpg passprhase

[source,bash]
----
unset GPG_PASSPHRASE
unset MAVEN_GPG_PASSPHRASE
----

After that, the staging repository must be closed, released and dropped. In the future, this will be automated.