= Release management

== Release strategy
While the extension is under heavy development, the plan is to provide the newest features for the LTS and the most current version of quarkus.

The version of the axon framework will be update as fast as possible.

The releases for the most current quarkus versions have the following pattern:

Major.Minor.Patchset

The releases for the latest LTS have a similar structure but it is extended by the quarkus version. Eg. for the current Quarkus LTS Version 3.15.* the version of the extension is 0.1.1-3.15.

In the link:docs/modules/ROOT/pages/index.adoc[documentation].

== How To Release
Sadly the setup github workflow doesn't work. As long as the workflow doesn't work, the release is created manually the local machine.

The following steps need to be followed.

For this example the version 0.4.1 should be released for the current and the latetst quarkus version.

_Release for the most current quarkus version_
[source,bash]
----
git checkout main
mvn -P ossrh -B release:prepare release:perform -DreleaseVersion=0.4.1 -DdevelopmentVersion=0.5.0-SNAPSHOT -Dgpg.passphrase="${GPG_PASSPHRASE}"
----

_Release for the latest quarkus LTS version_
[source,bash]
----
git checkout quarkus-3.15
mvn -P ossrh -B release:prepare release:perform -DreleaseVersion=0.4.1-3.15 -DdevelopmentVersion=0.5.0-3.15-SNAPSHOT -Dgpg.passphrase="${GPG_PASSPHRASE}"
----

After that the staging repository must be closed, released and dropped. In the future this will be automated.