= Event Processors

'''

link:index.adoc[Index]

link:05-04-CustomAggregateConfigurer.adoc[← Previous: Custom Aggregate Configurer]

link:05-06-TokenStores.adoc[Next: Token Stores →]

'''

Event Processors are necessary for event handler.
Those processors need to know which events are already processed.
This information is stored in a token store.

CAUTION: By default an in-memory token store is used. This normally shouldn't be used in production systems because on shutdown the token store is lost.

You can set the default event processor type by setting the property `quarkus.axon.event-processing.default-event-processing-type`.

== Tracking and Pooled Streaming Processor

For the tracking processor you can set properties for the default tracking processor using the properties of 'quarkus.axon.tracking processor' without a processor name. +
Those values are also used as default for the other defined tracking processors.

In the following example a default tracking processor is defined with a batch size of 100 and the initial position tail. +
The processor `processor1` inherits the batch size while it overrides the initial position using the value head. +
The processor `processor2` inherits the initial position while it overrides the batch size using value 10.

[source,properties]
----
quarkus.axon.trackingprocessor.batch-size=100
quarkus.axon.trackingprocessor.initial-position=tail
quarkus.axon.trackingprocessor.processor1.initial-position=head
quarkus.axon.trackingprocessor.processor2.batch-size=10
----

The same works for pooled processor with the following example:

[source,properties]
----
quarkus.axon.pooledprocessor.batch-size=100
quarkus.axon.pooledprocessor.initial-position=tail
quarkus.axon.pooledprocessor.processor1.initial-position=head
quarkus.axon.pooledprocessor.processor2.batch-size=10
----

With the exception of the persistent stream, the other processors need a token store where the information is stored, which events were already processed.

For more details on how to add a persistent token store, read link:05-06-TokenStores.adoc[Token Stores].

For details about the different event processors and the token store,
please read the documentation of the Axon framework.

== Persistent Stream Event Processors
Persistent streams are available, as soon as you have added the dependency for the link:05-02-EventStores.adoc[Axon Server Event Store].

For Persistent Streams it is not possible to set a default processor, which is used in the case, that `Subscribing Event Processors` should be used by default. The reason is that it wouldn't be possible
to use simple `Subscribing Event Processors` anymore.

Therefor the default `Persistent Stream Configuration` is only used to define default values for named configurations, what works equally to Tracking and Pooled Streaming Processor configuration.

The following example is equal to Tracking and Pooled Processing Processor configuration examples,
but for Persistent Stream Event Processors:

[source,properties]
----
quarkus.axon.persistentstreams.batch-size=100
quarkus.axon.persistentstreams.initial-position=tail
quarkus.axon.persistentstreams.processor1.initial-position=head
quarkus.axon.persistentstreams.processor2.batch-size=10
----

== Subscribing Event Processor

If you want to use a Subscribing Event Processor, you can set a name and you have to assign the processing groups, the processor is responsible for.

If you don't define a name, the name `Subscribing` is used. +
If you don't assign processing groups, no Subscribing Event Processor gets active.

This is an example of a configuration of the Subscribing Event Processor.

[source,properties]
----
quarkus.axon.subscribingprocessor.name=My-Subscribing-Processor
quarkus.axon.subscribingprocessor.processing-groups=GiftCardInMemory
----

== Persistent Stream Configuration Reference
include::includes/quarkus-axon-persistent-stream-eventprocessor.adoc[leveloffset=+1,opts=optional]

== Tracking Event Processor Configuration Reference
include::includes/quarkus-axon-tracking-eventprocessor.adoc[leveloffset=+1,opts=optional]

== Pooled Event Processor Configuration Reference
include::includes/quarkus-axon-pooled-eventprocessor.adoc[leveloffset=+1,opts=optional]


'''

link:index.adoc[Index]

link:05-04-CustomAggregateConfigurer.adoc[← Previous: Custom Aggregate Configurer]

link:05-06-TokenStores.adoc[Next: Token Stores →]