= Event Processors

'''

link:index.adoc[Index]

link:05-05-CustomAggregateConfigurer.adoc[← Previous: Custom Aggregate Configurer]

link:05-07-TokenStores.adoc[Next: Token Stores →]

'''

Event Processors are necessary for event handler.
Those processors need to know which events are already processed.
This information is stored in a token store.

CAUTION: By default an in-memory token store is used. This normally shouldn't be used in production systems because on shutdown the token store is lost.

You can set the default event processor type by setting the property `quarkus.axon.event-processing.default-event-processing-type`.

== Tracking and Pooled Streaming Processor

=== Default values
For the tracking processor you can set properties for the default tracking processor using the properties of 'quarkus.axon.tracking processor' without a processor name. +
Those values are also used as default for the other defined tracking processors.

In the following example a default tracking processor is defined with a batch size of 100 and the initial position tail. +
The processor `processor1` inherits the batch size while it overrides the initial position using the value head. +
The processor `processor2` inherits the initial position while it overrides the batch size using value 10.

[source,properties]
----
quarkus.axon.trackingprocessor.batch-size=100
quarkus.axon.trackingprocessor.initial-position=tail
quarkus.axon.trackingprocessor.processor1.initial-position=head
quarkus.axon.trackingprocessor.processor2.batch-size=10
----

The same works for pooled processor with the following example:

[source,properties]
----
quarkus.axon.pooledprocessor.batch-size=100
quarkus.axon.pooledprocessor.initial-position=tail
quarkus.axon.pooledprocessor.processor1.initial-position=head
quarkus.axon.pooledprocessor.processor2.batch-size=10
----

=== Random Processor Name

For this both processor types, you can define that the processor should be registered with a random name. This is useful, if you want to hold a In-Memory projection. Using a random processor name has the impact, that on startup all events are processed from the initial position.

To use a random name, you have to set the property `use-random-uuid-suffix` of the processor, or the default processor, to true.

In the following example for the processor1 a random name is used.

[source,properties]
----
quarkus.axon.pooledprocessor.processor1.use-random-uuid-suffix=true
----

=== Tokenstore

With the exception of the persistent stream, the other processors need a token store where the information is stored, which events were already processed.

By default the configured TokenStore is used(see link:05-07-TokenStores.adoc[Token Stores]). You have the possibility to override the default and use the In-Memory-Token-Store.

A Use case would be if you use it together with a random name to build an In-Memory-Projection.

For this case you have to set the property `use-in-memory-token-store` at the selected processor.

The following example sets the use of the In-Memory-Tokenstore as default for Tracking-Event-Processors:

[source,properties]
----
quarkus.axon.trackingprocessor.use-in-memory-token-store=true
----

In the next example, only the tracking processor with the name "MyTrackingProcessor" uses an In-Memory-Tokenstore:


[source,properties]
----
quarkus.axon.trackingprocessor.MyTrackingProcessor.use-in-memory-token-store=true
----

For details about the different event processors and the token store,
please read the documentation of the Axon framework.

== Persistent Stream Event Processors
Persistent streams are available as soon as you have added the dependency for the link:05-03-EventStores.adoc[Axon Server Event Store].

For Persistent Streams it is not possible to set a default processor, which is used in the case, that `Subscribing Event Processors` should be used by default. The reason is that it wouldn't be possible
to use simple `Subscribing Event Processors` anymore.

Therefor the default `Persistent Stream Configuration` is only used to define default values for named configurations, what works equally to Tracking and Pooled Streaming Processor configuration.

The following example is equal to Tracking and Pooled Processing Processor configuration examples,
but for Persistent Stream Event Processors:

[source,properties]
----
quarkus.axon.persistentstreams.batch-size=100
quarkus.axon.persistentstreams.initial-position=tail
quarkus.axon.persistentstreams.processor1.initial-position=head
quarkus.axon.persistentstreams.processor2.batch-size=10
----

Like for Pooling and Tracking Event Processors, you can define that the processor should be registered with a random name. This is useful, if you want to hold a In-Memory projection. Using a random processor name has the impact, that on startup all events are processed from the initial position.

To use a random name, you have to set the property `use-random-uuid-suffix` of the processor, or the default processor, to true.

In the following example for the processor1 a random name is used.

[source,properties]
----
quarkus.axon.persistentstreams.processor1.use-random-uuid-suffix=true
----

== Subscribing Event Processor

If you want to use a Subscribing Event Processor, you can set a name and you have to assign the processing groups, the processor is responsible for.

If you don't define a name, the name `Subscribing` is used. +
If you don't assign processing groups, no Subscribing Event Processor gets active.

This is an example of a configuration of the Subscribing Event Processor.

[source,properties]
----
quarkus.axon.subscribingprocessor.name=My-Subscribing-Processor
quarkus.axon.subscribingprocessor.processing-groups=GiftCardInMemory
----

== Persistent Stream Configuration Reference
include::includes/quarkus-axon-persistent-stream-eventprocessor.adoc[leveloffset=+1,opts=optional]

== Tracking Event Processor Configuration Reference
include::includes/quarkus-axon-tracking-eventprocessor.adoc[leveloffset=+1,opts=optional]

== Pooled Event Processor Configuration Reference
include::includes/quarkus-axon-pooled-eventprocessor.adoc[leveloffset=+1,opts=optional]


'''

link:index.adoc[Index]

link:05-05-CustomAggregateConfigurer.adoc[← Previous: Custom Aggregate Configurer]

link:05-07-TokenStores.adoc[Next: Token Stores →]