= Event Stores
:toc:
:toclevels: 3

'''
link:index.adoc[Index]

link:05-02-CommandHandler.adoc[← Previous: CommandHandler]

link:05-04-Snapshots.adoc[Next: Snapshots →]

'''

CAUTION: By default, the In-Memory Event Store is used. This normally shouldn't be used in production systems because on shutdown the events are lost.

== Axon Server

Add the dependency

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-server</artifactId>
    <version>VERSION</version>
</dependency>
----

When starting with dev or test profile, the Axon Server is started as dev service. For production use the connection details can be configured using the keys

[source, properties]
----
quarkus.axon.server.context=default
quarkus.axon.server.servers=localhost
quarkus.axon.server.default-grpc-port=8124
----

All you have to do is to define the correct servers, the default port for the axon servers if not defined, and context if they don't match the default value.

If you want to connect to a axon server cluster with three nodes, where the nodes are named node1, node2 and node3, and all are listening to port 8124 you can configure it as follows:

[source, properties]
----
quarkus.axon.server.servers=node1;node2;node3
----

If the node2 listens to port 9999 the the configuration would look like this:

[source, properties]
----
quarkus.axon.server.servers=node1;node2:9999;node3
----

If all nodes, except node 2, listen to the port 1024 the the configuration could look like this:
[source, properties]
----
quarkus.axon.server.servers=node1;node2:9999;node3
quarkus.axon.server.default-grpc-port=1024
----

In some cases it is necessary to increase the grpc message size. Eg if you want to increase the max grpc message size to 1 MB you can it like this:

[source, properties]
----
quarkus.axon.server.grpc.maxMessageSize.value=1
quarkus.axon.server.grpc.maxMessageSize.unit=MB
----

=== Security

==== Authentication
For authentication you can set a token in the application.properties or as environment variable.

For Details see <<_axon_server_configuration_reference>>

If you want to force, that the API Token is set, you can set the property `quarkus.axon.server.token-required` to true. If the token is required, but not set, a startup failure happens.

==== SSL
If you have configured the Axon Server for SSL connections, but the certificate is not issued by a
trusted certificate authority, you can configure a trust store. Based on Axoniqs documentation, this must be a
pem keystore.

[source, properties]
----
quarkus.axon.server.sslTrustStore=/path/to/keystore.pem
----

=== DevService
By default, as mentioned above, an Axon-Server is started with dev and test profile.
If you want to disable the DevService only for the Axon-Server you have the possibility to do that
in the application.properties.

[source,properties]
----
quarkus.axon.server.dev-services.enabled=false
----

== JPA Event Store

Add the dependency

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-jpa-eventstore</artifactId>
    <version>${project.version}</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.
Finally, you have to define in application.properties e.g.

[source,properties]
----
quarkus.hibernate-orm.database.generation=update
----

or somehow set up the necessary tables(e.g. using Flyway). For details see the Axoniq documentation.

There are some configurations possible(see <<_jpa_event_store_configuration_reference>>)

== JDBC Event Store

Add the dependency

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-jpa-eventstore</artifactId>
    <version>${project.version}</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.

By default the database structures are created automatically.

CAUTION: The supported database for "autocreate-tables" are limited to mariadb, mysql, postgresql and oracle

You can disable it by setting

[source,properties]
----
quarkus.axon.eventstore.jdbc.autocreate-tables=false
----

There are some other configurations possible(see <<_jdbc_event_store_configuration_reference>>)

== Custom Event Store
To provide your custom event store, you just have to implement the interface EventstoreConfigurer.

Here is an example of what it could look like:

[source,java]
----
@ApplicationScoped
public class MyCustomEventstoreConfigurer implements EventstoreConfigurer {


    public void configure(Configurer configurer) {
        configurer.configureEventStore(this::myCustomEventstore);
    }

    private EventStore myCustomEventstore(Configuration conf) {
        // here you setup your custom event store
    }
}
----
For more details of how to setup an event store, please read the Axon framework documentation.

== Configuration References
[#_axon_server_configuration_reference]
=== Axon Server Configuration Reference
include::includes/quarkus-axon-server.adoc[leveloffset=+1,opts=optional]

[#_jpa_event_store_configuration_reference]
=== JPA Event Store Configuration Reference
include::includes/quarkus-axon-jpa-eventstore.adoc[leveloffset=+1,opts=optional]

[#_jdbc_event_store_configuration_reference]
=== JDBC Event Configuration Reference
include::includes/quarkus-axon-jdbc-eventstore.adoc[leveloffset=+1,opts=optional]

'''
link:index.adoc[Index]

link:05-02-CommandHandler.adoc[← Previous: CommandHandler]

link:05-04-Snapshots.adoc[Next: Snapshots →]