= Sagas

'''

link:index.adoc[Index]

link:05-07-EventUpcasting.adoc[← Previous: Event Upcasting]

link:05-09-ExceptionHandling.adoc[Next: Exception Handling →]

'''

[CAUTION]
====
Sagas require an Eventprocessor, but the default Token Store is only in Memory.

Beware to configure a Token Store for procution usage.
====

Sagas are automatically registered.

Application Scoped Beans are injected.

There are different Saga stores supported.

CAUTION: By default the in memory Saga store is active. This is not recommended for production use.

The available Saga stores are:

- InMemory Saga store
- JDBC Saga store
- JPA Saga store

A Saga is similar to an Event handler. You have to implmement methods, which listen to events which are annotated with `@SagaEventHandler`.

Furthermore one method must be annotated with `@StartSaga`, and another one must be annotated with `@EndSaga`.

Example:

[source,java]
----
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY) // <1>
public class CardReturnSaga {

    @Inject
    private transient CardReturnService cardReturnService; // <2>

    @StartSaga
    @SagaEventHandler(associationProperty = "id", keyName = "cardId")
    void handle(Api.CardGotEmptyEvent event) {
        cardReturnService.cardBecameEmpty(); // <3>
    }

    @EndSaga
    @SagaEventHandler(associationProperty = "id", keyName = "cardId")
    void handle(Api.CardReturnedEvent event) {
        cardReturnService.cardWasReturned();// ... <4>
    }
}
----
<1> Necessary annotation, that this Saga is registered with field for serialization, if the serializer cannot access fields(see link:05-19-Serialization.adoc[Serialization])
<2> An application scoped bean is injected. It must be transient because of serialization
<3> the application scoped bean is used to do some necessary task
<4> the application scoped bean is used to do some necessary task

For more details about how to implement Sagas please read the Axon framework documentation.

== InMemory Saga Store
For development purposes you can use the in memory saga store. It is active by default.

== JDBC Saga store

If you would like to use the JDBC Sagastore, you simply have to add the dependency to the project and set up a datasource in quarkus.

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-sagastore-jdbc</artifactId>
    <version>VERSION</version>
</dependency>
----

NOTE: The dependency quarkus-axon-transaction for transaction management is automatically added. For detailed information see link:05-14-Transaction.adoc[Transaction].

By default the database table is created on startup. If you don't want to create the table automatically, you can disable the creation.

There are some configurations possible(see <<_jdbc_sagastore_configuration>>)

== JPA Saga store
If you would like to use the JPA Sagastore, you simply have to add the dependency to the project and set up a datasource in quarkus.

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-sagastore-jpa</artifactId>
    <version>VERSION</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.
Finally, you have to define in application.properties e.g.

[source,properties]
----
quarkus.hibernate-orm.database.generation=update
----

or somehow set up the necessary tables(e.g. using Flyway). For details see the Axoniq documentation.

[#_jdbc_sagastore_configuration]
=== JDBC Sagastore configuration
include::includes/quarkus-axon-sagastore-jdbc.adoc[leveloffset=+1,opts=optional]

'''

link:index.adoc[Index]

link:05-07-EventUpcasting.adoc[← Previous: Event Upcasting]

link:05-09-ExceptionHandling.adoc[Next: Exception Handling →]