= Event Stores
:toc:
:toclevels: 3

'''
link:index.adoc[Index]

link:05-00-SetupAndUsage.adoc[← Previous: Setup & Usage]

link:05-02-Snapshots.adoc[Next: Snapshots →]

'''

CAUTION: By default, the In-Memory Event Store is used. This normally shouldn't be used in production systems because on shutdown the events are lost.

== Axon Server

Add the dependency

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-server</artifactId>
    <version>VERSION</version>
</dependency>
----

When starting with dev or test profile, the Axon Server is started as dev service. For production use the connection details can be configured using the keys

[source, properties]
----
quarkus.axon.server.context=default
quarkus.axon.server.hostname=localhost
quarkus.axon.server.grpc-port=8124
----

All you have to do is to define the correct host name, port and context if they don't match the default value.

=== Security
For authentication you can set a token in the application.properties or as environment variable.

For Details see <<_axon_server_configuration_reference>>

If you want to force, that the API Token is set, you can set the property `quarkus.axon.server.token-required` to true. If the token is required, but not set, a startup failure happens.

== JPA Event Store

Add the dependency

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-jpa-eventstore</artifactId>
    <version>${project.version}</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.
Finally, you have to define in application.properties e.g.

[source,properties]
----
quarkus.hibernate-orm.database.generation=update
----

or somehow set up the necessary tables(e.g. using Flyway). For details see the Axoniq documentation.

There are some configurations possible(see <<_jpa_event_store_configuration_reference>>)

== JDBC Event Store

Add the dependency

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-jpa-eventstore</artifactId>
    <version>${project.version}</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.

By default the database structures are created automatically.

CAUTION: The supported database for "autocreate-tables" are limited to mariadb, mysql, postgresql and oracle

You can disable it by setting

[source,properties]
----
quarkus.axon.eventstore.jdbc.autocreate-tables=false
----

There are some other configurations possible(see <<_jdbc_event_store_configuration_reference>>)

== Custom Event Store
To provide your custom event store, you just have to implement the interface EventstoreConfigurer.

Here is an example of what it could look like:

[source,java]
----
@ApplicationScoped
public class MyCustomEventstoreConfigurer implements EventstoreConfigurer {


    public void configure(Configurer configurer) {
        configurer.configureEventStore(this::myCustomEventstore);
    }

    private EventStore myCustomEventstore(Configuration conf) {
        // here you setup your custom event store
    }
}
----
For more details of how to setup an event store, please read the Axon framework documentation.

== Configuration References
[#_axon_server_configuration_reference]
=== Axon Server Configuration Reference
include::includes/quarkus-axon-server.adoc[leveloffset=+1,opts=optional]

[#_jpa_event_store_configuration_reference]
=== JPA Event Store Configuration Reference
include::includes/quarkus-axon-jpa-eventstore.adoc[leveloffset=+1,opts=optional]

[#_jdbc_event_store_configuration_reference]
=== JDBC Event Configuration Reference
include::includes/quarkus-axon-jdbc-eventstore.adoc[leveloffset=+1,opts=optional]

'''
link:index.adoc[Index]

link:05-00-SetupAndUsage.adoc[← Previous: Setup & Usage]

link:05-02-Snapshots.adoc[Next: Snapshots →]