= Interceptors

[#_command_dispatch_interceptors_]
== Command Dispatch Interceptors
If you'd like to set up command dispatch interceptors, you have to implement `CommandDispatchInterceptorsProducer`.The method of the interface returns a list of interceptors in the order they should be invoked.

A simple example would be to log each command message, which was dispatched to the command bus.

[source,java]
----
@ApplicationScoped
public static class MyCommandDispatchInterceptorsProducer implements CommandDispatchInterceptorsProducer {

    @Override
    public List<MessageDispatchInterceptor<CommandMessage<?>>> createDispatchInterceptor() {
        return List.of(interceptor());
    }

    private @NotNull MessageDispatchInterceptor<CommandMessage<?>> interceptor() {
        return messages -> (index, command) -> {
            Log.debugf("Dispatching the command: %s", command);
            return command;
        };
    }

}
----

Another use case could be the structural validation of the command using Bean Validation.

Please read the Axon framework documentation for details about the Command disptach interceptor.

[#_command_handler_interceptor]
== Command Handler Interceptor

If you'd like to set up command handler interceptors, you have to implement `CommandHandlerInterceptorsProducer`.The method of the interface returns a list of interceptors in the order they should be invoked.

Example:

[source,java]
----
@ApplicationScoped
public static class MyCommandHandlerInterceptorsProducer implements CommandHandlerInterceptorsProducer {

    @Override
    public List<MessageHandlerInterceptor<CommandMessage<?>>> createHandlerInterceptor() {
        return List.of(interceptor1(), interceptor2());
    }

    private @NotNull MessageHandlerInterceptor<CommandMessage<?>> interceptor1() {
        return (unitOfWork, interceptorChain) -> {
            // Details <1>
            return interceptorChain.proceed(); // <2>
        };
    }

    private @NotNull MessageHandlerInterceptor<CommandMessage<?>> interceptor2() {
        return (unitOfWork, interceptorChain) -> {
            // Details <1>
            return interceptorChain.proceed(); // <2>
        };
    }

}
----
<1> The details of your interceptor have to be implemented here
<2> Continues the chain of interceptors

For more details about command handler interceptors, please read the Axon framework documentation.

== Query Dispatch Interceptors
In the same way as for <<_command_dispatch_interceptors_>> you can implement an interceptor when queries are dispatched.

The interface you have to implement is ´QueryDispatchInterceptorsProducer´.

== Query Handler Interceptors
In the same way as for <<_command_handler_interceptor>> you can implement an interceptor when queries are handled.

The interface you have to implement is ´QueryHandlerInterceptorsProducer´.

== Event Dispatch Interceptors
In the same way as for <<_command_dispatch_interceptors_>> you can implement an interceptor when events are dispatched.

The interface you have to implement is ´EventDispatchInterceptorsProducer´.

== Event Handler Interceptors
In the same way as for <<_command_handler_interceptor>> you can implement an interceptor when events are handled.

The interface you have to implement is ´EventHandlerInterceptorsProducer´.

These interceptors are registered for each event processor.

'''

link:index.adoc[Index]

link:05-10-ExceptionHandling.adoc[← Previous: Exception Handling]

link:05-14-InjectCdiBeans.adoc[Next: Inject CDI Beans into Message Handler Methods →]