= Health Checks

If the quarkus extension for health checks (quarkus-smallrye-health) is added, checks for the Axon Server connection and for the event processors are activated.

Axon Server connection health checks are only active if you have added the extension quarkus-axon-server to your project.

If you would like to deactivate the health checks, you can do that by setting the properties(just one or both) to false.

[source,properties]
----
quarkus.axon.health-enabled=false #<1>
quarkus.axon.server.health-enabled=false #<2>
----
<1> disables the health checks for the event processors
<2> disables the health check for the connection to the axon server

Be aware that these settings are build-time settings. That means that these settings are considered at build time only. You can't overrule this setting at runtime e.g., using an environment variable.


'''

link:index.adoc[Index]

link:05-16-Tracing.adoc[← Previous: Tracing]

link:05-18-AccessToAxonObjects.adoc[Next: Access To Axon Objects →]