= Serialization

By default, the Jackson ObjectMapper of Quarkus is used for Axon converters. It is the same ObjectMapper that is used for REST services.

If you need to adapt that ObjectMapper, keep in mind that serialization for REST services is changed as well.

If you want to configure only the conversion of Axon related data, you can implement `AxonConverterProducer`.

To enable Jackson Blackbird only for Axon's default converters, set:

[source,properties]
----
quarkus.axon.serialization.blackbird.enabled=true
----

== Use-cases for custom converters

=== Events or value objects are not records and do not follow the Bean Standard
If your events or one of the classes in their object hierarchy does not follow the Bean Standard, configure an event converter through `AxonConverterProducer.createEventConverter()`.

=== Event Sourced Entities and Entities do hide its fields
If snapshotting is activated and Event Sourced Entities hide their fields, configure a general converter through `AxonConverterProducer.createGeneralConverter()`.

=== Commands or Queries are not records, and its object hierarchies do not follow the Bean Standard
If your commands, queries, or one of the classes in their object hierarchy does not follow the Bean Standard, configure a message converter through `AxonConverterProducer.createMessageConverter()`.

'''

link:index.adoc[Index]

link:05-19-AccessToAxonObjects.adoc[← Previous: Access To Axon Objects]
