= Quarkus Axonframework Extension
include::./includes/attributes.adoc[]

This guide explains how to use quarkus together with the axon framework.

== What is Quarkus Axonframework

Axon Framework assists developers in implementing message-driven applications. That means that you can implement applications using Event Sourcing and CQRS.

== Creating an Event Sourcing Application

=== The domain

Gift cards can be issued with an initial amount. +
Those gift cards can then be used for payments. +
Under some circumstances, it is necessary to cancel the last payment.

=== Example architecture
The model handles the commands.

A rest service for requesting the current amount of the card uses a query. The query is handled by an in-memory projection.

The commands are submitted by a test.

=== Getting started (after 0.1.0-RC1)

Add the following import to your build file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon</artifactId>
    <version>VERSION</version>
</dependency>
----

==== Compatibility matrix & supported versions
The latest LTS and the current version quarkus are supported. Axon framework is updated as soon as it is released, updated in the extension running without error.

|===
| Extension Version | Quarkus | Axon framework

| 0.1.0-RC5 | 3.17.5 | 4.10.4
| 0.1.0-RC4 | 3.17.4 | 4.10.4
| 0.1.0-RC3 | 3.16.4 | 4.10.3
| 0.1.0-RC2 | 3.16.4 | 4.10.3
| 0.1.0-RC1 | 3.16.2 | 4.10.3

| 0.1.0-quarkus-3.15-RC4 | 3.15.2 | 4.10.4
| 0.1.0-quarkus-3.15-RC3 | 3.15.2 | 4.10.3
| 0.1.0-quarkus-3.15-RC2 | 3.15.2 | 4.10.3
| 0.1.0-quarkus-3.15-RC1 | 3.15.1 | 4.10.3
|===


You can now create the commands, events and the model.

==== Events and Commands

[source,java]
----
public class Api {
    public record IssueCardCommand(@TargetAggregateIdentifier String id, int initialAmount) { }
    public record CardIssuedEvent(String id, int amount) { }
    public record RedeemCardCommand(@TargetAggregateIdentifier String id, int amount) { }
    public record CardRedeemedEvent(String id, int amount) { }
    public record UndoLatestRedemptionCommand(@TargetAggregateIdentifier String id, int amount) { }
    public record LatestRedemptionUndoneEvent(String id, int amount) { }
}
----

==== Model

The model contains the domain logic. It contains the handlers

* CommandHandler and
* EventSourcingHandler

As an example for a domain service, the Command UndoLatestRedemptionCommand is handled not by the root aggregate, but by a domain service.

The EventSourcingHandler methods are necessary for tracking the state of the aggregate, which is used for validation.

[source,java]
----
public class Giftcard {

    @AggregateIdentifier
    private String id;
    private int currentAmount;
    private final List<Integer> cardRedemptions = new ArrayList<>();

    Giftcard() { // <1>
        // necesarry for the axon framework
    }

    @CommandHandler
    Giftcard(Api.IssueCardCommand command) { // <2>
        if (command == null) {
            throw new IllegalArgumentException("command mustn't be null");
        }
        apply(new Api.CardIssuedEvent(command.id(), command.initialAmount())); // <3>
        Log.infof("new card with the id %s and the initial amount %s was issued", command.id(), command.initialAmount());
    }

    @EventSourcingHandler
    void handle(Api.CardIssuedEvent event) { // <4>
        this.id = event.id();
        this.currentAmount = event.amount();
    }

    @CommandHandler
    void handle(Api.RedeemCardCommand command) { // <2>
        if (this.currentAmount < command.amount()) {
            throw new IllegalArgumentException(
                    "amount(" + command.amount() + ") must be less than current card amount(" + currentAmount + ")");
        }
        apply(new Api.CardRedeemedEvent(id, command.amount())); // <3>
        Log.infof("card was redeemed by %s", command.amount());
    }

    @EventSourcingHandler
    void handle(Api.CardRedeemedEvent event) { // <4>
        this.currentAmount -= event.amount();
        cardRedemptions.add(event.amount());
    }

    public void undoRedemption(int amount) { // <5>
        Optional<Integer> lastestRedeemedAmount = lastestRedeemedAmount();
        if (lastestRedeemedAmount.isEmpty() || lastestRedeemedAmount.get() != amount) {
            throw new IllegalArgumentException("amount must be the lastest redeem amount");
        } else {
            apply(new Api.LatestRedemptionUndoneEvent(id, amount));
            Log.infof("latest redemption was undone");
        }
    }

    private Optional<Integer> lastestRedeemedAmount() {
        if (!cardRedemptions.isEmpty()) {
            return Optional.of(cardRedemptions.get(cardRedemptions.size() - 1));
        }
        return Optional.empty();
    }

    @EventSourcingHandler
    void handle(Api.LatestRedemptionUndoneEvent event) { // <4>
        cardRedemptions.remove(cardRedemptions.size() - 1);
        this.currentAmount += event.amount();
    }

    @ExceptionHandler
    public void handleAll(Exception exception) {
        throw new CommandExecutionException("wrapped exception in details", exception);
    }

}
----
<1> An empty constructor is necessary for the axon framework that it is able to load the aggregate from the event store and apply its events
<2> the command handler methods, which handle the requested commands
<3> the event is applied if the validation was successful
<4> the event sourcing handler methods, which are invoked when an aggregate is read from the repository and when a command handling method applies an event
<5> this methode is executed by the domain service


===== Domain service
The domain service gets the repository for the gift card injected. +
It handles the undo command by loading the aggregate from the repository and then invoking a method on the aggregate.

This is useful if one command modifies more aggregates.

[source,java]
----
@ApplicationScoped
public class DomainServiceExample {

    @Inject
    Repository<Giftcard> giftcardRepository; // <1>

    @CommandHandler
    void handle(Api.UndoLatestRedemptionCommand command) { // <2>
        Aggregate<Giftcard> giftcardAggregate = giftcardRepository.load(command.id()); // <3>
        giftcardAggregate.execute(giftcard -> giftcard.undoRedemption(command.amount())); // <4>
    }

    @ExceptionHandler
    public void handleAll(Exception exception) {
        throw new CommandExecutionException("wrapped exception in details", exception);
    }

}

----
<1> the axon repository is injected
<2> the handler method for the command
<3> First the aggregate is read, using the injected repository
<4> A method of the aggregate is executed

==== Projection
The current amount is built and queried using a projection.

The project listens to the necessary events using the annotation EventHandler
and updates the amount of each gift card in memory in a simple map.
In production systems, this information should be persisted e.g., in a database.

It also handles the query with a method annotated by QueryHandler.
It gets the amount from the in memory map and returns the id and the amount of the card.

[source, java]
----
public record GiftcardQuery(String id) { }
----

[source,java]
----
@ApplicationScoped
public class GiftcardProjection {

    private final Map<String, GiftcardDto> giftcards = new HashMap<>();

    @QueryHandler
    GiftcardDto handle(GiftcardQuery query) { // <1>
        return giftcards.get(query.id());
    }

    @EventHandler
    void handle(Api.CardIssuedEvent event) { // <2>
        giftcards.put(event.id(), new GiftcardDto(event.id(), event.amount()));
    }

    @EventHandler
    void handle(Api.CardRedeemedEvent event) { // <2>
        giftcards.get(event.id()).redeem(event.amount());
    }

    @EventHandler
    void handle(Api.LatestRedemptionUndoneEvent event) { // <2>
        giftcards.get(event.id()).undoLatestRedemption(event.amount());
    }
}

----
<1> The handler method for the query request, which return the gift card with the requested id
<2> The event handler methods, which are necessary to project the current amounts of each gift card

A rest service gets the QueryGateway injected and queries a card by id, using the GiftcardQuery.

[source,java]
----
@Path("giftcard")
public class GiftcardResource {

    @Inject
    QueryGateway queryGateway;

    @GET
    public Uni<GiftcardDto> getGiftcard(@RestQuery String id) {
        return Uni.createFrom()
                .future(() -> queryGateway.query(new GiftcardQuery(id), GiftcardDto.class));
    }

}
----

==== Test

The test submits the commands using the injected CommandGateway. +
It uses the rest service to verify the expected current amount of the gift card. +
It also verifies that exceptions are thrown if commands are not valid.

[source,java]
----
@QuarkusTest
@TestHTTPEndpoint(GiftcardResource.class)
class ApplicationTest {

    @Inject
    CommandGateway commandGateway; // <1>

    @Test
    void wholeUseCaseTest() {
        var cardId = UUID.randomUUID().toString();
        commandGateway.sendAndWait(new Api.IssueCardCommand(cardId, 20)); // <2>
        commandGateway.sendAndWait(new Api.RedeemCardCommand(cardId, 2)); // <3>
        commandGateway.sendAndWait(new Api.RedeemCardCommand(cardId, 4)); // <3>
        commandGateway.sendAndWait(new Api.RedeemCardCommand(cardId, 3)); // <3>

        assertThatException().isThrownBy(() -> commandGateway.sendAndWait(new Api.RedeemCardCommand(cardId, 12))) // <4>
                .havingCause()
                .withMessageContaining("must be less than current card amount");

        RestAssured.given().queryParam("id", cardId)
                .when().get()
                .then()
                .body("id", CoreMatchers.equalTo(cardId), "currentAmount", CoreMatchers.equalTo(11));

        commandGateway.sendAndWait(new Api.UndoLatestRedemptionCommand(cardId, 3)); // <5>
        assertThatException().isThrownBy(() -> commandGateway.sendAndWait(new Api.UndoLatestRedemptionCommand(cardId, 2))) // <6>
                .havingCause()
                .withMessageContaining("amount must be the lastest redeem amount");

        RestAssured.given().queryParam("id", cardId)
                .when().get()
                .then()
                .body("id", CoreMatchers.equalTo(cardId), "currentAmount", CoreMatchers.equalTo(14));
    }

}
----
<1> The CommandGateway of the Axon framework is injected, to be able to send commands. This also works in production classes
<2> A new gift card is requested
<3> Some payments are requested. Those payments are valid because the card amount is still greater.
<4> A payment is requested with an amount, greater than the current amount of the gift card -> an error is expected
<5> A cancellation of the last valid payment is requested
<6> A cancallation of the last valid payment with the wrong amount is requested -> an error is expected



=== Event Stores

CAUTION: By default, the In-Memory Event Store is used. This normally shouldn't be used in production systems because on shutdown the events are lost.

Currently, you have to options to use another event store. Either use the extension "quarkus-axon-server" or implement your own custom event store by implementing the interface "EventstoreConfigurer".

In future releases at the least the jdbc event store will be added as an extra extension.

==== Axon Server connection

Add the dependency

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-server</artifactId>
    <version>VERSION</version>
</dependency>
----

When starting with dev or test profile, the Axon Server is started as dev service. For production use the connection details can be configured using the keys

[source, properties]
----
quarkus.axon.server.context=default
quarkus.axon.server.hostname=localhost
quarkus.axon.server.grpc-port=8124
----

All you have to do is to define the correct host name, port and context if they don't match the default value.

==== JPA Event Store

Add the dependency

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-jpa-eventstore</artifactId>
    <version>${project.version}</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.
Finally, you have to define in application.properties e.g.

[source,properties]
----
quarkus.hibernate-orm.database.generation=update
----

or somehow set up the necessary tables(e.g. using Flyway). For details see the Axoniq documentation.

There are some configurations possible(see <<_jpa_event_store_configuration>>)

==== JDBC Event Store

Add the dependency

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-jpa-eventstore</artifactId>
    <version>${project.version}</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.

By default the database structures are created automatically.

CAUTION: The supported database for "autocreate-tables" are limited to mariadb, mysql, postgresql and oracle

You can disable it by setting

[source,properties]
----
quarkus.axon.eventstore.jdbc.autocreate-tables=false
----

There are some other configurations possible(see <<_jdbc_event_store_configuration>>)

==== Custom Event Store
To provide your custom event store, you just have to implement the interface blabla.

Here is an example of what it could look like:

[source,java]
----
@ApplicationScoped
public class MyCustomEventstoreConfigurer implements EventstoreConfigurer {


    public void configure(Configurer configurer) {
        configurer.configureEventStore(this::myCustomEventstore);
    }

    private EventStore myCustomEventstore(Configuration conf) {
        // here you setup your custom event store
    }
}
----
For more details of how to setup an event store, please read the Axon framework documentation.

=== Snapshots

To enable snapshots, you have to configure

- the trigger type and
- set a JSON annotation at the Root Aggregate and it's Entities

Both values can be configured per aggregate and also as default.

CAUTION: When a snapshot is created, the aggregate is serialized using JSON.

You have to take care that all properties of the aggregate are serialized.
If fields of a Class(Root Aggregate, Value Objects, Entities) do not have accessors,
a possibility is to add the annotation `@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)` to the Class.

This strategy was chosen because it doesn't have an impact on the serialization of other classes(e.g. the return values of Web Services).

Maybe this behavior can be improved in the future releases of the extension.

==== Trigger Types
Currently, three types are available:

— no-snapshots
- event-count
- load-time

no-snapshots: is the default value and disables snapshots.

event-count: If the aggregate exceeds the maximum threshold, a snapshot is taken.

load-time: If the time for loading the events of an aggregate exceeds the maximum threshold, a snapshot is taken.

==== Configuration

To change the default behavior to event-count with a threshold of 500, add the following lines to the application.properties:
[source,properties]
----
quarkus.axon.snapshots.trigger-type=event-count
quarkus.axon.snapshots.threshold=500
----

To change the behavior for the Aggregate `at.meks.quarkiverse.axon.shared.model.Giftcard` to load-time and the threshold 750 millis, add the following lines to the application.properties.

[source,properties]
----
quarkus.axon.snapshots."at.meks.quarkiverse.axon.shared.model.Giftcard".trigger-type=load-time
quarkus.axon.snapshots."at.meks.quarkiverse.axon.shared.model.Giftcard".threshold=750
----

==== Implement your own Aggregate-Configurer

If you decide to provode your own Aggregate-Configurer, which creates, Axon's `AggregateConfiguration` you can implement the interface `at.meks.quarkiverse.axon.runtime.api.QuarkusAggregateConfigurer`.

For each Aggregate, the method `createConfigurer`. This method returns Axon's `AggregateConfiguration`

=== Event Processors

Event Processors are necessary for event handler.
Those processors need to know which events are already processed.
This information is stored in a token store.

CAUTION: By default, the subscribing processor with an in-memory token store is used. This normally shouldn't be used in production systems because on shutdown the token store is lost.

The different processors can be used by adding the dependency the one, you would like to use.

The artifact ids are:

- quarkus-axon-persistent-stream-eventprocessor
- quarkus-axon-pooled-eventprocessor
- quarkus-axon-tracking-eventprocessor

With the exception of the persistent stream, the other processors need a token store where the information is stored, which events were already processed.

For more details on how to add a persistent token store, read the section <<Tokenstore>>.

For details about the different event processors and the token store,
please read the documentation of the Axon framework.

=== Persistent Stream Event Processors
Because of an unexpected behaviour when configuring the event store default source for the event processors, it was necessary to register a persistent stream per package, where event processors are located.

Furthermore, it was necessary to create a name for the persistent stream, which is as unique as possible on the server side. Therefore, the name is created based on the application name and the package name. The configurable stream name and source name of the persistent stream are currently not available. Currently, it is unknown if they come back.

=== Tokenstore
CAUTION: By default, an in-memory token store is used. This normally shouldn't be used in production systems because on shutdown the token store is lost.

Currently, only the JDBC Tokenstore is supported.

==== JDBC Tokenstore
If you would like to use the JDBC Tokenstore, you simply have to add the dependency to the project and set up a datasource in quarkus.

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-tokenstore-jdbc</artifactId>
    <version>VERSION</version>
</dependency>
----

By default the database table is created on startup. If you don't want to create the table automatically, you can disable the creation.

CAUTION: Normally in production environment you need a proper transaction manager configured in the axon framework. For detailed information see <<Transaction>>.

[source,properties]
----
quarkus.axon.tokenstore.autocreate-table-for-jdbc-token=false
----

Currently it is not supported to have more than 1 configured datasource.

==== JPA Tokenstore
If you would like to use the JPA Tokenstore you simply have to add the dependency to the project, and setup a datasource in quarkus.

[source, xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-tokenstore-jpa</artifactId>
    <version>VERSION</version>
</dependency>
----

Set up your hibernate/datasource configuration in application.properties.
Finally, you have to define in application.properties e.g.

[source,properties]
----
quarkus.hibernate-orm.database.generation=update
----

or somehow set up the necessary tables(e.g. using Flyway). For details see the Axoniq documentation.

There are some configurations possible(see <<_jpa_tokenstore_configuration>>)


==== Custom Tokenstore
To provide your custom tokenstore you just need to implement the interface "TokenStoreConfigurer".

[source,java]
----
@ApplicationScoped
public class MyCustomTokenStoreConfigurer implements TokenStoreConfigurer {

    @Override
    public void configureTokenStore(Configurer configurer) {
        configureAndSetupTokenstore(configurer.eventProcessing());
        configurer.registerComponent(TokenStore.class, this::createTokenStore);
    }

    private TokenStore createTokenStore(Configuration configuration) {
        // setup your token store here
    }
}
----

For more information on setting up a token store, please read the Axon framework documentation.

=== Upcasting
To provide upcasters in the defined order, you have to provide a instance of EventUpcasterChain.

[source,java]
----
@Produces
EventUpcasterChain eventUpcasterChain() {
    producedChain = new EventUpcasterChain(
            new ComplaintEvent0_to_1Upcaster(), // <1>
            new ComplaintEvent1_to_2Upcaster()
    );

    return producedChain;
}
----
<1> The list of your upcasters

=== Sagas

[CAUTION]
====
Sagas require an Eventprocessor, but the default Token Store is only in Memory.

Beware to configure a Token Store for procution usage.
====

Sagas are automatically registered.

There are different Saga stores supported.

CAUTION: By default the in memory Saga store is active. This is not recommended for production use.

The available Saga stores are:

- InMemory Saga store
- JDBC Saga store
- JPA Saga store

A Saga is similar to an Event handler. You have to implmement methods, which listen to events which are annotated with `@SagaEventHandler`.

Furthermore one method must be annotated with `@StartSaga`, and another one must be annotated with `@EndSaga`.

Example:

[source,java]
----
public class CardReturnSaga {

    @StartSaga
    @SagaEventHandler(associationProperty = "id", keyName = "cardId")
    void handle(Api.CardGotEmptyEvent event) {
        // ... <1>
    }

    @EndSaga
    @SagaEventHandler(associationProperty = "id", keyName = "cardId")
    void handle(Api.CardReturnedEvent event) {
        // ... <2>
    }
}
----
<1> The code for handling the event is omitted
<2> The code for handling the event is omitted

For more details about how to implement Sagas please read the Axon framework documentation.

==== InMemory Saga Store
For development purposes you can use the in memory saga store. It is active by default.

==== JDBC Saga store
TODO

==== JPA Saga store
TODO

=== Exception Handling

==== Handling Exceptions in Command Handler

Automatically all Exceptions, which are thrown in Command-Handler-Methods, are wrapped into `CommandExecutionException`.

To disable this feature, set the following configuration variable:

[source,properties]
----
quarkus.axon.exception-handling.wrap-on-command-handler=false
----

==== Handling Exceptions in Query Handler

Automatically all Exceptions, which are thrown in Query-Handler-Methods, are wrapped into `QueryExecutionException`.

To disable this feature, set the following configuration variable:

[source,properties]
----
quarkus.axon.exception-handling.wrap-on-query-handler=false
----

=== Interceptors
[#_command_dispatch_interceptors_]
==== Command Dispatch Interceptors
If you'd like to set up command dispatch interceptors, you have to implement `CommandDispatchInterceptorsProducer`.The method of the interface returns a list of interceptors in the order they should be invoked.

A simple example would be to log each command message, which was dispatched to the command bus.

[source,java]
----
@ApplicationScoped
public static class MyCommandDispatchInterceptorsProducer implements CommandDispatchInterceptorsProducer {

    @Override
    public List<MessageDispatchInterceptor<CommandMessage<?>>> createDispatchInterceptor() {
        return List.of(interceptor());
    }

    private @NotNull MessageDispatchInterceptor<CommandMessage<?>> interceptor() {
        return messages -> (index, command) -> {
            Log.debugf("Dispatching the command: %s", command);
            return command;
        };
    }

}
----

Another use case could be the structural validation of the command using Bean Validation.

Please read the Axon framework documentation for details about the Command disptach interceptor.

[#_command_handler_interceptor]
==== Command Handler Interceptor

If you'd like to set up command handler interceptors, you have to implement `CommandHandlerInterceptorsProducer`.The method of the interface returns a list of interceptors in the order they should be invoked.

Example:

[source,java]
----
@ApplicationScoped
public static class MyCommandHandlerInterceptorsProducer implements CommandHandlerInterceptorsProducer {

    @Override
    public List<MessageHandlerInterceptor<CommandMessage<?>>> createHandlerInterceptor() {
        return List.of(interceptor1(), interceptor2());
    }

    private @NotNull MessageHandlerInterceptor<CommandMessage<?>> interceptor1() {
        return (unitOfWork, interceptorChain) -> {
            // Details <1>
            return interceptorChain.proceed(); // <2>
        };
    }

    private @NotNull MessageHandlerInterceptor<CommandMessage<?>> interceptor2() {
        return (unitOfWork, interceptorChain) -> {
            // Details <1>
            return interceptorChain.proceed(); // <2>
        };
    }

}
----
<1> The details of your interceptor have to be implemented here
<2> Continues the chain of interceptors

For more details about command handler interceptors, please read the Axon framework documentation.

==== Query Dispatch Interceptors
In the same way as for <<_command_dispatch_interceptors_>> you can implement an interceptor when queries are dispatched.

The interface you have to implement is ´QueryDispatchInterceptorsProducer´.

==== Query Handler Interceptors
In the same way as for <<_command_handler_interceptor>> you can implement an interceptor when queries are handled.

The interface you have to implement is ´QueryHandlerInterceptorsProducer´.

==== Event Dispatch Interceptors
In the same way as for <<_command_dispatch_interceptors_>> you can implement an interceptor when events are dispatched.

The interface you have to implement is ´EventDispatchInterceptorsProducer´.

==== Event Handler Interceptors
In the same way as for <<_command_handler_interceptor>> you can implement an interceptor when events are handled.

The interface you have to implement is ´EventHandlerInterceptorsProducer´.

These interceptors are registered for each event processor.

=== Inject CDI Beans into Message Handler Methods

Application scoped beans can be injected in message handler methods. The beans are injected into methods annotated with

* CommandHandler
* QueryHandler and
* EventHandler


Here is a simple example of an injection into a command handler.

[source,java]
----
@CommandHandler
void handle(MyCommand command, MyBean bean) {
    // ...
    bean.doBeanStuff();
    // ...
}
----

=== Transaction

CAUTION: By default, no transaction management is setup.

If you need transaction management, you can add the extension:

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-transaction</artifactId>
    <version>VERSION</version>
</dependency>
----

It uses the quarkus transaction management configured into the axon framework.

=== Metrics
If you want to use metrics you can enable it by adding the extension:

[source,xml]
----
<dependency>
    <groupId>at.meks.quarkiverse.axonframework-extension</groupId>
    <artifactId>quarkus-axon-metrics</artifactId>
    <version>VERSION</version>
</dependency>
----

Using the configuration, you can disable the metrics:
[source,properties]
----
quarkus.axon.metrics.enabled=false
----

Futhermore axon provides the possibility to use tag for the metrics. This is enabled by default but can also be disbabled using the configuration:
[source,properties]
----
quarkus.axon.metrics.with-tags=false
----

=== Health Checks

If the quarkus extension for health checks (quarkus-smallrye-health) is added, checks for the Axon Server connection and for the event processors are activated.

Axon Server connection health checks are only active if you have added the extension quarkus-axon-server to your project.

If you would like to deactivate the health checks, you can do that by setting the properties(just one or both)

- quarkus.axon.health-enabled
- quarkus.axon.server.health-enabled

to false. Be aware that these settings are build-time settings. That means that these settings are considered at build time only. You can't overrule this setting at runtime e.g., using an environment variable.

=== Access to Axon objects

If you need to access the

- EventBus
- EventGateway
- CommandBus
- CommandGateway
- QueryBus
- QueryGateway or
- a aggregate repository

you can simply inject it to your CDI bean. The repository and the command gateway injection is shown in the example above.

[[extension-configuration-reference]]
== Extension Configuration Reference

=== Core configuration
include::includes/quarkus-axon.adoc[leveloffset=+1,opts=optional]

=== Metrics configuration
include::includes/quarkus-axon-metrics.adoc[leveloffset=+1,opts=optional]

=== Eventprocessor configurations

==== Persistent Stream
include::includes/quarkus-axon-persistent-stream-eventprocessor.adoc[leveloffset=+1,opts=optional]

==== Tracking Event Processor configuration
include::includes/quarkus-axon-tracking-eventprocessor.adoc[leveloffset=+1,opts=optional]

==== Pooled Event Processor configuration
include::includes/quarkus-axon-pooled-eventprocessor.adoc[leveloffset=+1,opts=optional]

==== JDBC Tokenstore configuration
include::includes/quarkus-axon-tokenstore-jdbc.adoc[leveloffset=+1,opts=optional]

[#_jpa_tokenstore_configuration]
==== JPA Tokenstore configuration
include::includes/quarkus-axon-tokenstore-jpa.adoc[leveloffset=+1,opts=optional]

=== Axon Server configuration
include::includes/quarkus-axon-server.adoc[leveloffset=+1,opts=optional]

[#_jpa_event_store_configuration]
=== JPA Event Store configuration
include::includes/quarkus-axon-jpa-eventstore.adoc[leveloffset=+1,opts=optional]

[#_jdbc_event_store_configuration]
=== JDBC Event Store configuration
include::includes/quarkus-axon-jdbc-eventstore.adoc[leveloffset=+1,opts=optional]