quarkus.axon.axon-application-name=IntegrationTests
quarkus.axon.snapshots.trigger-type=event-count
quarkus.axon.snapshots.threshold=2
quarkus.axon.command-gateway.retry.scheduling.fixed-retry-interval-millis=100
quarkus.axon.command-gateway.retry.scheduling.max-retry-count=10
quarkus.axon.pooledprocessor.pooled1.initial-segments=4
quarkus.axon.pooledprocessor.pooled1.namespaces=GiftCardInMemory
quarkus.axon.pooledprocessor.pooled2.namespaces=EventProcessorGroup4
quarkus.axon.pooledprocessor.pooled2.use-in-memory-token-store=true
quarkus.axon.pooledprocessor.pooled2.use-random-uuid-suffix=true
quarkus.axon.pooledprocessor.pooled3.namespaces=EventProcessorGroup8
quarkus.axon.pooledprocessor.pooled3.use-in-memory-token-store=true
quarkus.axon.pooledprocessor.pooled4.namespaces=at.meks.quarkiverse.axon.shared.projection
quarkus.axon.pooledprocessor.pooled5.namespaces=EventProcessorGroup5
quarkus.axon.pooledprocessor.pooled5.use-random-uuid-suffix=true
quarkus.axon.pooledprocessor.pooled5.use-in-memory-token-store=true
quarkus.axon.pooledprocessor.pooled6.namespaces=EventProcessorGroup9
quarkus.axon.pooledprocessor.pooled6.use-in-memory-token-store=true
# todo reactivate as soon as persistent streams are available
#quarkus.axon.persistentstreams.streams1.processing-groups=at.meks.quarkiverse.axon.shared.projection2, EventProcessorGroup6
# workaround via pooled processor
quarkus.axon.pooledprocessor.pooled7.namespaces=at.meks.quarkiverse.axon.shared.projection2, EventProcessorGroup6
quarkus.axon.subscribingprocessor.namespaces=EventProcessorGroup7
quarkus.datasource.db-kind=postgresql
quarkus.axon.server.storage-engine=dcb
quarkus.axon.server.dev-services.use-dcb=true